export const LOAD_GREETING_SUCCESS = 'LOAD_GREETING_SUCCESS';
export const LOAD_SONGS_BY_NAME_SUCCESS = 'LOAD_SONGS_BY_NAME_SUCCESS';
export const LOAD_API_SETTINGS_SUCCESS = 'LOAD_API_SETTINGS_SUCCESS';
export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';
export const UPDATE_TODAYS_DATE_SUCCESS = 'UPDATE_TODAYS_DATE_SUCCESS';