export const LOAD_GREETING_SUCCESS = 'LOAD_GREETING_SUCCESS';
export const LOAD_SONGS_BY_NAME_SUCCESS = 'LOAD_SONGS_BY_NAME_SUCCESS';
export const LOAD_API_SETTINGS_SUCCESS = 'LOAD_API_SETTINGS_SUCCESS';